image: node

stages:
  - test
  - build
  - deploy

before_script:
  - whoami
  - pwd

test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website && npm install && npm run start &
    - wait-on http://localhost:3000/ --httpTimeout 30000 && blc --recursive --exclude-external http://localhost:3000

vulnerabilities check:
  stage: test
  script:
    - cd website && npm install && npm run scan

build site:
  stage: build
  cache:
    key: build-site
    policy: push
    paths:
      - ./website/build/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h
    paths:
      - ./website/build/test-site
  script:
    - cd website && npm install && npm run build

deploy to staging:
  stage: deploy
  variables:
    CNAME: staging-corujam-cicd.surge.sh
    GIT_STRATEGY: none
  cache:
    key: build-site
    policy: pull
  before_script:
    - npm install -g surge
  script:
    - surge -p website/build/test-site -d ${CNAME}
  after_script:
    - whoami
  environment:
    name: staging
    url: http://${CNAME}
  only:
    - develop

deploy to production:
  stage: deploy
  variables:
    NAME: corujam-cicd.surge.sh
    GIT_STRATEGY: none
  cache:
    key: build-site
    policy: pull
  before_script:
    - npm install -g surge
  script:
    - surge -p website/build/test-site -d ${CNAME}
  after_script:
    - whoami
  environment:
    name: production
    url: http://${CNAME}
  only:
    - master
