image: node

stages:
  - build
  - test
  - deploy

build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h
    paths:
      - ./website/build/test-site
  script:
    - cd website/
    - npm install
    - npm run build
