image: node

stages:
  - build
  - test
  - deploy

build site:
  stage: build
  artifacts:
    paths:
      - ./website/build/test-site
  script:
    - cd website/
    - npm install
    - npm run build
