image: node

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - ./website/build/

before_script:
  - whoami
  - pwd

test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000/ --timeout 15000
    - blc --recursive --exclude-external http://localhost:3000

build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h
    paths:
      - ./website/build/test-site
  script:
    - cd website/
    - npm install
    - npm run build

deploy website:
  stage: deploy
  before_script:
    - npm install -g surge
    - echo "corujam-cicd.surge.sh" > website/build/test-site/CNAME
  script:
    - surge website/build/test-site
  after_script:
    - whoami
  environment:
    name: staging
    url: http://corujam-cicd.surge.sh
  only:
    - develop
